### ISSUE TITLE
json_macros incompatible with rustc-serialize

### ISSUE THREAD

**Issue by ArtemGr** [tomjakubowski/json_macros#12]
Linking with json_macros prevents the program from using rustc-serialize.
Test case: https://gist.github.com/ArtemGr/96f45adaf2e16f3e16d4

Funny enough, the offending part is `extern crate "rustc-serialize" as rustc_serialize;` in json_macros/src/macro.rs: when I strip maro.rs to
```
#![crate_name="json_macros"]
#![feature(plugin_registrar, quote)]
#![allow(unstable)]

extern crate rustc;
extern crate syntax;
//extern crate "rustc-serialize" as rustc_serialize;

use syntax::ast::TokenTree;
use syntax::codemap::Span;
use syntax::ext::base::{ExtCtxt, MacResult, DummyResult};
use rustc::plugin::Registry;

#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
    reg.register_macro("json", expand);
}

fn expand<'cx>(_: &'cx mut ExtCtxt, sp: Span,
               _: &[TokenTree]) -> Box<MacResult + 'cx> {
    return DummyResult::expr(sp);
}

```
everything links okay again, but when I add the `extern crate "rustc-serialize" as rustc_serialize;` line to macro.rs I get the linking error.

**Comment by tomjakubowski** [comment]
I think you should be able to fix this by ensuring your link to `json_macros` looks like:

```rust
#[plugin] #[no_link] extern crate json_macros
```

Linking to syntax extensions by mistake can be the source of these linker errors.

**Comment by ArtemGr** [comment]
Oh, thanks, I didn't know that!
