### ISSUE TITLE
serde support

### ISSUE THREAD

**Issue by tomjakubowski** [tomjakubowski/json_macros#19]
as a Cargo feature -- `json_serde!` macro? or just make `json!` emit serde stuff?

**Comment by yberreby** [comment]
I have implemented serde support on a fork: https://github.com/yberreby/json_macros/commit/7680e14b7c6fa8177a1e54b961b84f56de309b89

I'll see if I can turn it into a cargo feature.

**Comment by tomjakubowski** [comment]
Done in https://github.com/tomjakubowski/json_macros/pull/25 and cargo featurified on master. Thanks @yberreby !

**Comment by yberreby** [comment]
You may want to update the README, which, as of now, only mentions `serde`, and doesn't tell the user about the Cargo features.

**Comment by tomjakubowski** [comment]
Thanks for the reminder. I was going to do a pass over the README and Travis configuration in a little bit. 😄
