### ISSUE TITLE
Support serde 0.8

### ISSUE THREAD

**Issue by dtolnay** [tomjakubowski/json_macros#29]
From a brief look at the code, I think this is as simple as bumping the serde and serde_json dependencies from "^0.6" to ">=0.6, <0.9" because none of the APIs you use have changed in 0.7 or 0.8.

**Comment by tomjakubowski** [comment]
Sorry for letting this slip. That sounds good to me! I don't have a great Rust development environment set up at the moment, but if you (or anyone else!) would like to contribute an MR to set the dependency to `">= 0.6, < 0.9", I'd be happy to review it.

**Comment by dtolnay** [comment]
Superseded by #34.
